apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  annotations:
    agent.severalnines.com/ccr-stamp: 97a33d3eadc5b2c46acd6b1e7dfc6fb50bcc247f22071b0fd19052215bec8cd5
    secrets.severalnines.com/source-sha256: 297851c3e0fd439be4042c5fa2e890686dd11eb1eb907c14adea02974d21f737
  labels:
    secrets.severalnines.com/managed-by: sops-ccr-pipeline
    secrets.severalnines.com/source-name: test
    secrets.severalnines.com/source-namespace: default
  name: test-sops
  namespace: default
sops:
  age:
  - enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZKzZkeTRvNkxaeXpkazZs
      dXpPbGgxVlExUmlZRVNFSGxLNmNnSUVNTFNjClkvc3UwbndtU1lmMUxmb3hMbWU4
      RTRxd2NXSk5McHl6czA5akdkdkp2NjgKLS0tIEVDQy9NSS9MbmNiNEdrd3VjUjNL
      aWduV0MvczRTa3YzbDZtU2kzVGdJU0kKK54/MwNXV4/PpZQjQjsPZgxg57pQqzFZ
      lI++KJqqa3b1rjK73etFlS0mO7Q6c24AE7WG2JNLNmrRJR19N5J2Dw==
      -----END AGE ENCRYPTED FILE-----
    recipient: age1qnlev68mc5frn7hhy27rawcxl03zrwj08vjp63qmr2dvelwaqeeq0yaesn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T13:33:27Z"
  mac: ENC[AES256_GCM,data:leEgCYBonlDi5hw0p3iWiSCDAGaBQ5ZxOErWXDkveJx+uKW9DdNGW001U6OCfqUX+qRn+03tMo9UyDSBHhGa7bK94aJu3WT1/9tTlzOc3Im5hQJcbIl6KOH60+0ZuBAXYqburNJLn/nnOvTH0PWX9oXS0jzuBmbPSPm9zLVGmzM=,iv:pW+adt4PcRuONVIxB97+B6cpi3rKmpjOXDzNg+bv8Ak=,tag:lXzHk9A9PCHyqT13Febx8g==,type:str]
  version: 3.13.1
spec:
  secretTemplates:
  - annotations:
      agent.severalnines.com/expose-keys: access-key-id,secret-access-key,endpoint,region,use-ssl,provider
    labels:
      agent.severalnines.com/cc-secret-id: "2"
      agent.severalnines.com/cc-secret-name: test
      agent.severalnines.com/expose: "true"
      agent.severalnines.com/secret: cloud
      agent.severalnines.com/secret-provider: s3
      agent.severalnines.com/secret-type: s3
      secrets.severalnines.com/managed-by: sops-ccr-pipeline
    name: test
    stringData:
      access-key-id: ENC[AES256_GCM,data:Jng8,iv:Zydh/STrRS/hObZibAJ6JZFAA8Xv3V3j36Z1kCt5KHA=,tag:zVFeGT8PM/vBj1XnukrA/Q==,type:str]
      endpoint: ENC[AES256_GCM,data:KXG8LDc=,iv:XnRsJcQQ+RuNeyFC2QJjTHI3sUvtlSryz06r+YSiYUQ=,tag:/vIfHBRmEf0NoYPkL8yFDw==,type:str]
      provider: ENC[AES256_GCM,data:Kbw=,iv:qt11mJQD/naXV1/9F7jsUm6bcgeRYTJMZ6MHlv2i5xY=,tag:IUn3j08qrFxwMbqdLknuvw==,type:str]
      region: ""
      secret-access-key: ENC[AES256_GCM,data:+NwR,iv:fLgID1EMIXN5F4EEBqHuMduIz4NVyl3oKHjOJkeh7pM=,tag:vkdkLrWOEGkUJ4oz+DlS5g==,type:str]
      use-ssl: ENC[AES256_GCM,data:0QwDlA==,iv:WnJLb+YG8yqBqkwcKO/1E8tyfx3ew9dROxDMOBpDDas=,tag:sohw1busANDhC3UWpgRkXw==,type:str]
    type: Opaque
  suspend: false

